# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
sudo: required
dist: trusty

r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

os:
  - linux

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

group: edge
